[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0xd3ca91e31d37f7b0a3a5b8d29253aaaf75d8aabddad52e0107b499ebe3779d73'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]